# Import API Data and Export to SQL

## Set up API connection and parameters

In [14]:
import http.client
import requests, json
import pandas as pd

conn = http.client.HTTPSConnection("skyscanner-skyscanner-flight-search-v1.p.rapidapi.com")

headers = {
    'x-rapidapi-host': "skyscanner-skyscanner-flight-search-v1.p.rapidapi.com",
    'x-rapidapi-key': "0577c9d754msh6a149580eb6ccffp1b7c56jsn2b2ab82bc33c"
    }

In [30]:
# Origin airport:
origins = ["HOU-iata","JFK-iata","LAX-iata","DFW-iata","DEN-iata"]

# Destination airports: 
destinations = ["HOU-iata","JFK-iata","LAX-iata","DFW-iata","DEN-iata","ATL-iata","ORD-iata","CLT-iata","LAS-iata","PHX-iata","PCO-iata","SEA-iata","MIA-iata","FLL-iata","SFO-iata","EWR-iata","MSP-iata","DTW-iata","BOS-iata","SLC-iata","PHL-iata","BWI-iata","TPA-iata","SAN-iata","AMA-iata","IAD-iata","BNA-iata","ABQ-iata","PDX-iata","DSM-iata","MSY-iata","BIL-iata","FAR-iata","MAF-iata","LBB-iata","BTV-iata","ROA-iata","MKE-iata","MSN-iata","GRB-iata","CYS-iata","JAC-iata","ELP-iata","CRP-iata","BHM-iata","HSV-iata","TUS-iata","LIT-iata","FAT-iata","SMF-iata","GJT-iata","BDL-iata","EYW-iata","PFN-iata","BOI-iata","EVV-iata","AZO-iata","AUS-iata","SAT-iata","MAF-iata"]

# Enter date as YYYY-MM-DD:
date = "2021-09-03"

# Other parameters
currancy = "USD"
originCountry = "US"
locale = "en-US"
baseURL = "https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com/apiservices/browseroutes/v1.0/"

## Loop through destinations and origins to obtain list of flights

In [31]:
airports = {}
flights = {}
listlist = []
from time import sleep

for destination in destinations:
    for origin in origins:
        
        myurl = baseURL + originCountry + "/" + currancy + "/" + locale + "/" + origin + "/"  + destination + "/" + date
        response = requests.request("GET", myurl, headers=headers)
        results = json.loads(response.text)
        listlist.append(results)

        if("Quotes" in results):
            
            # Add to "airports" to create way to tie airport code back to airport name
            for Places in results["Places"]:
                airports[Places["PlaceId"]] = Places["Name"] 
            
            # Print data as it is pulled from API to track progress
            for Quotes in results["Quotes"]:
                print("***************")
                ori = Quotes["OutboundLeg"]["OriginId"]
                dest = Quotes["OutboundLeg"]["DestinationId"]
                price = Quotes["MinPrice"]
                print(f"${price} USD |{airports[ori]}| {airports[dest]} ")
                flights[airports[dest]] = price
                sleep(2.5)

print("-------------------------------")
print("DONE!")

***************
$88 USD |New York John F. Kennedy| Houston George Bush Intercntl.
***************
$40 USD |Los Angeles International| Houston George Bush Intercntl.
***************
$51 USD |Dallas Fort Worth International| Houston George Bush Intercntl.
***************
$79 USD |Dallas Fort Worth International| Houston George Bush Intercntl.
***************
$25 USD |Denver International| Houston George Bush Intercntl.
***************
$110 USD |Houston George Bush Intercntl.| New York John F. Kennedy
***************
$294 USD |Houston George Bush Intercntl.| New York John F. Kennedy
***************
$172 USD |Los Angeles International| New York John F. Kennedy
***************
$207 USD |Los Angeles International| New York John F. Kennedy
***************
$131 USD |Dallas Fort Worth International| New York John F. Kennedy
***************
$172 USD |Dallas Fort Worth International| New York John F. Kennedy
***************
$107 USD |Denver International| New York John F. Kennedy
***************
$159 USD |Denver International| New York John F. Kennedy
***************
$41 USD |Houston George Bush Intercntl.| Los Angeles International
***************
$138 USD |New York John F. Kennedy| Los Angeles International
***************
$38 USD |Dallas Fort Worth International| Los Angeles International
***************
$40 USD |Denver International| Los Angeles International
***************
$55 USD |Houston George Bush Intercntl.| Dallas Fort Worth International
***************
$79 USD |Houston George Bush Intercntl.| Dallas Fort Worth International
***************
$129 USD |New York John F. Kennedy| Dallas Fort Worth International
***************
$40 USD |Los Angeles International| Dallas Fort Worth International
***************
$48 USD |Denver International| Dallas Fort Worth International
***************
$28 USD |Houston George Bush Intercntl.| Denver International
***************
$165 USD |New York John F. Kennedy| Denver International
***************
$184 USD |New York John F. Kennedy| Denver International
***************
$43 USD |Los Angeles International| Denver International
***************
$56 USD |Dallas Fort Worth International| Denver International
***************
$63 USD |Dallas Fort Worth International| Denver International
***************
$41 USD |Houston George Bush Intercntl.| Atlanta Hartsfield-Jackson
***************
$124 USD |New York John F. Kennedy| Atlanta Hartsfield-Jackson
***************
$48 USD |Los Angeles International| Atlanta Hartsfield-Jackson
***************
$62 USD |Los Angeles International| Atlanta Hartsfield-Jackson
***************
$51 USD |Dallas Fort Worth International| Atlanta Hartsfield-Jackson
***************
$85 USD |Dallas Fort Worth International| Atlanta Hartsfield-Jackson
***************
$43 USD |Denver International| Atlanta Hartsfield-Jackson
***************
$50 USD |Houston George Bush Intercntl.| Chicago O'Hare International
***************
$139 USD |Houston George Bush Intercntl.| Chicago O'Hare International
***************
$144 USD |New York John F. Kennedy| Chicago O'Hare International
***************
$259 USD |New York John F. Kennedy| Chicago O'Hare International
***************
$59 USD |Los Angeles International| Chicago O'Hare International
***************
$59 USD |Dallas Fort Worth International| Chicago O'Hare International
***************
$60 USD |Dallas Fort Worth International| Chicago O'Hare International
***************
$49 USD |Denver International| Chicago O'Hare International
***************
$52 USD |Denver International| Chicago O'Hare International
***************
$64 USD |Houston George Bush Intercntl.| Charlotte Douglas
***************
$130 USD |Houston George Bush Intercntl.| Charlotte Douglas
***************
$148 USD |New York John F. Kennedy| Charlotte Douglas
***************
$338 USD |Los Angeles International| Charlotte Douglas
***************
$80 USD |Dallas Fort Worth International| Charlotte Douglas
***************
$248 USD |Dallas Fort Worth International| Charlotte Douglas
***************
$56 USD |Denver International| Charlotte Douglas
***************
$68 USD |Denver International| Charlotte Douglas
***************
$47 USD |Houston George Bush Intercntl.| Las Vegas Mccarran
***************
$63 USD |Houston George Bush Intercntl.| Las Vegas Mccarran
***************
$187 USD |New York John F. Kennedy| Las Vegas Mccarran
***************
$209 USD |New York John F. Kennedy| Las Vegas Mccarran
***************
$43 USD |Los Angeles International| Las Vegas Mccarran
***************
$76 USD |Dallas Fort Worth International| Las Vegas Mccarran
***************
$100 USD |Dallas Fort Worth International| Las Vegas Mccarran
***************
$41 USD |Denver International| Las Vegas Mccarran
***************
$88 USD |Houston George Bush Intercntl.| Phoenix Sky Harbor
***************
$98 USD |New York John F. Kennedy| Phoenix Sky Harbor
***************
$61 USD |Los Angeles International| Phoenix Sky Harbor
***************
$79 USD |Los Angeles International| Phoenix Sky Harbor
***************
$60 USD |Dallas Fort Worth International| Phoenix Sky Harbor
***************
$38 USD |Denver International| Phoenix Sky Harbor
***************
$95 USD |Houston George Bush Intercntl.| Seattle / Tacoma International
***************
$150 USD |Houston George Bush Intercntl.| Seattle / Tacoma International
***************
$149 USD |New York John F. Kennedy| Seattle / Tacoma International
***************
$92 USD |Los Angeles International| Seattle / Tacoma International
***************
$130 USD |Dallas Fort Worth International| Seattle / Tacoma International
***************
$132 USD |Dallas Love Field| Seattle / Tacoma International
***************
$44 USD |Denver International| Seattle / Tacoma International
***************
$63 USD |Houston George Bush Intercntl.| Miami International
***************
$130 USD |Houston George Bush Intercntl.| Miami International
***************
$80 USD |New York John F. Kennedy| Miami International
***************
$78 USD |Los Angeles International| Miami International
***************
$119 USD |Los Angeles International| Miami International
***************
$99 USD |Dallas Fort Worth International| Miami International
***************
$255 USD |Dallas Fort Worth International| Miami International
***************
$31 USD |Denver International| Miami International
***************
$48 USD |Houston George Bush Intercntl.| Fort Lauderdale International
***************
$59 USD |Houston George Bush Intercntl.| Fort Lauderdale International
***************
$99 USD |New York John F. Kennedy| Fort Lauderdale International
***************
$33 USD |Los Angeles International| Fort Lauderdale International
***************
$88 USD |Los Angeles International| Fort Lauderdale International
***************
$60 USD |Dallas Fort Worth International| Fort Lauderdale International
***************
$60 USD |Dallas Fort Worth International| Fort Lauderdale International
***************
$25 USD |Denver International| Fort Lauderdale International
***************
$104 USD |Houston George Bush Intercntl.| San Francisco International
***************
$119 USD |Houston George Bush Intercntl.| San Francisco International
***************
$146 USD |New York John F. Kennedy| San Francisco International
***************
$39 USD |Los Angeles International| San Francisco International
***************
$96 USD |Dallas Fort Worth International| San Francisco International
***************
$171 USD |Dallas Love Field| San Francisco International
***************
$89 USD |Denver International| San Francisco International
***************
$74 USD |Houston George Bush Intercntl.| New York Newark
***************
$113 USD |Houston George Bush Intercntl.| New York Newark
***************
$67 USD |Los Angeles International| New York Newark
***************
$193 USD |Los Angeles International| New York Newark
***************
$57 USD |Dallas Fort Worth International| New York Newark
***************
$115 USD |Dallas Fort Worth International| New York Newark
***************
$54 USD |Denver International| New York Newark
***************
$189 USD |Denver International| New York Newark

***************
$75 USD |Houston George Bush Intercntl.| Minneapolis St Paul
***************
$119 USD |Houston George Bush Intercntl.| Minneapolis St Paul
***************
$190 USD |New York John F. Kennedy| Minneapolis St Paul
***************
$239 USD |New York John F. Kennedy| Minneapolis St Paul
***************
$57 USD |Los Angeles International| Minneapolis St Paul
***************
$85 USD |Dallas Fort Worth International| Minneapolis St Paul
***************
$29 USD |Denver International| Minneapolis St Paul
***************
$43 USD |Houston George Bush Intercntl.| Detroit Wayne County
***************
$193 USD |New York John F. Kennedy| Detroit Wayne County
***************
$33 USD |Los Angeles International| Detroit Wayne County
***************
$77 USD |Los Angeles International| Detroit Wayne County
***************
$62 USD |Dallas Fort Worth International| Detroit Wayne County
***************
$26 USD |Denver International| Detroit Wayne County
***************
$64 USD |Houston George Bush Intercntl.| Boston Logan International
***************
$213 USD |Houston George Bush Intercntl.| Boston Logan International
***************
$85 USD |New York John F. Kennedy| Boston Logan International
***************
$78 USD |Los Angeles International| Boston Logan International
***************
$132 USD |Los Angeles International| Boston Logan International
***************
$85 USD |Dallas Fort Worth International| Boston Logan International
***************
$189 USD |Dallas Fort Worth International| Boston Logan International
***************
$54 USD |Denver International| Boston Logan International
***************
$125 USD |Denver International| Boston Logan International
***************
$72 USD |Houston George Bush Intercntl.| Salt Lake City
***************
$141 USD |Houston George Bush Intercntl.| Salt Lake City
***************
$108 USD |New York John F. Kennedy| Salt Lake City
***************
$49 USD |Los Angeles International| Salt Lake City
***************
$92 USD |Dallas Fort Worth International| Salt Lake City
***************
$31 USD |Denver International| Salt Lake City
***************
$56 USD |Houston George Bush Intercntl.| Philadelphia International
***************
$64 USD |Houston George Bush Intercntl.| Philadelphia International
***************
$141 USD |New York John F. Kennedy| Philadelphia International
***************
$1432 USD |New York John F. Kennedy| Philadelphia Trenton-Mercer
***************
$57 USD |Los Angeles International| Philadelphia International
***************
$349 USD |Los Angeles International| Philadelphia International
***************
$53 USD |Dallas Fort Worth International| Philadelphia International
***************
$49 USD |Denver International| Philadelphia International
***************
$76 USD |Denver International| Philadelphia International
***************
$2495 USD |New York John F. Kennedy| Baltimore Glenn L Martin
***************
$2124 USD |Dallas Fort Worth International| Baltimore Glenn L Martin
***************
$40 USD |Houston George Bush Intercntl.| Tampa International
***************
$108 USD |New York John F. Kennedy| Tampa International
***************
$38 USD |Los Angeles International| Tampa International
***************
$37 USD |Dallas Fort Worth International| Tampa International
***************
$40 USD |Dallas Fort Worth International| Tampa International
***************
$36 USD |Denver International| Tampa International
***************
$68 USD |Denver International| Tampa International
***************
$64 USD |Houston George Bush Intercntl.| San Diego International
***************
$112 USD |New York John F. Kennedy| San Diego International
***************
$59 USD |Los Angeles International| San Diego International
***************
$95 USD |Dallas Fort Worth International| San Diego International
***************
$218 USD |Dallas Fort Worth International| San Diego International
***************
$56 USD |Denver International| San Diego International
***************
$121 USD |Denver International| Amarillo International
***************
$133 USD |Denver International| Amarillo International
***************
$109 USD |Houston George Bush Intercntl.| Washington Dulles
***************
$152 USD |Houston George Bush Intercntl.| Washington Dulles
***************
$180 USD |New York John F. Kennedy| Washington Dulles
***************
$3016 USD |New York John F. Kennedy| Washington Dulles
***************
$108 USD |Los Angeles International| Washington Dulles
***************
$189 USD |Los Angeles International| Washington Dulles
***************
$103 USD |Dallas Fort Worth International| Washington Dulles
***************
$152 USD |Dallas Fort Worth International| Washington Dulles
***************
$99 USD |Denver International| Washington Dulles
***************
$74 USD |Houston George Bush Intercntl.| Nashville
***************
$136 USD |Houston George Bush Intercntl.| Nashville
***************
$207 USD |New York John F. Kennedy| Nashville
***************
$274 USD |New York John F. Kennedy| Nashville
***************
$58 USD |Los Angeles International| Nashville
***************
$139 USD |Dallas Fort Worth International| Nashville
***************
$49 USD |Denver International| Nashville
***************
$75 USD |Denver International| Nashville
***************
$120 USD |Houston George Bush Intercntl.| Albuquerque
***************
$141 USD |Houston George Bush Intercntl.| Albuquerque
***************
$117 USD |Los Angeles International| Albuquerque
***************
$150 USD |Los Angeles International| Albuquerque
***************
$160 USD |Dallas Fort Worth International| Albuquerque
***************
$256 USD |Dallas Fort Worth International| Albuquerque
***************
$186 USD |Denver International| Albuquerque
***************
$3001 USD |Denver International| Albuquerque
***************
$97 USD |Houston George Bush Intercntl.| Portland
***************
$179 USD |Houston George Bush Intercntl.| Portland
***************
$141 USD |New York John F. Kennedy| Portland
***************
$84 USD |Los Angeles International| Portland
***************
$139 USD |Los Angeles International| Portland
***************
$108 USD |Dallas Fort Worth International| Portland
***************
$150 USD |Dallas Love Field| Portland
***************
$48 USD |Denver International| Portland
***************
$136 USD |Houston George Bush Intercntl.| Des Moines
***************
$270 USD |Houston George Bush Intercntl.| Des Moines
***************
$212 USD |New York John F. Kennedy| Des Moines
***************
$40 USD |Houston George Bush Intercntl.| New Orleans Louis Armstrong
***************
$164 USD |New York John F. Kennedy| New Orleans Louis Armstrong
***************
$214 USD |New York John F. Kennedy| New Orleans Louis Armstrong
***************
$51 USD |Los Angeles International| New Orleans Louis Armstrong
***************
$130 USD |Los Angeles International| New Orleans Louis Armstrong
***************
$28 USD |Dallas Fort Worth International| New Orleans Louis Armstrong
***************
$56 USD |Denver International| New Orleans Louis Armstrong
***************
$79 USD |Denver International| New Orleans Louis Armstrong
***************
$172 USD |Dallas Fort Worth International| Billings
***************
$197 USD |Dallas Fort Worth International| Billings
***************
$192 USD |Los Angeles International| Fargo
***************
$99 USD |Denver International| Fargo
***************
$87 USD |Dallas Fort Worth International| Midland Odessa Regional
***************
$196 USD |Dallas Fort Worth International| Midland Odessa Regional
***************
$212 USD |Dallas Fort Worth International| Lubbock International
***************
$3025 USD |Dallas Fort Worth International| Lubbock International
***************
$94 USD |New York John F. Kennedy| Burlington
***************
$262 USD |Denver International| Burlington
***************
$374 USD |Denver International| Burlington
***************
$203 USD |Los Angeles International| Roanoke
***************
$121 USD |Houston George Bush Intercntl.| Milwaukee General Mitchell
***************
$201 USD |New York John F. Kennedy| Milwaukee General Mitchell

***************
$65 USD |Los Angeles International| Milwaukee General Mitchell
***************
$86 USD |Dallas Fort Worth International| Milwaukee General Mitchell
***************
$159 USD |Denver International| Milwaukee General Mitchell
***************
$110 USD |Houston George Bush Intercntl.| Madison
***************
$266 USD |New York John F. Kennedy| Madison
***************
$130 USD |Dallas Fort Worth International| Madison
***************
$305 USD |Dallas Fort Worth International| Madison
***************
$73 USD |Denver International| Madison
***************
$1765 USD |Denver International| Cheyenne
***************
$184 USD |New York John F. Kennedy| Jackson Hole
***************
$446 USD |New York John F. Kennedy| Jackson Hole
***************
$133 USD |Denver International| Jackson Hole
***************
$169 USD |Denver International| Jackson Hole
***************
$113 USD |Houston George Bush Intercntl.| El Paso International
***************
$114 USD |Houston George Bush Intercntl.| El Paso International
***************
$232 USD |New York John F. Kennedy| El Paso International
***************
$129 USD |Dallas Fort Worth International| El Paso International
***************
$205 USD |Dallas Fort Worth International| El Paso International
***************
$53 USD |Denver International| El Paso International
***************
$202 USD |New York John F. Kennedy| Corpus Christi International
***************
$122 USD |Los Angeles International| Birmingham
***************
$123 USD |Dallas Fort Worth International| Birmingham
***************
$250 USD |Dallas Fort Worth International| Birmingham
***************
$109 USD |Houston George Bush Intercntl.| Huntsville International
***************
$144 USD |Dallas Fort Worth International| Tucson International
***************
$249 USD |Denver International| Tucson International
***************
$100 USD |Houston George Bush Intercntl.| Fresno Yosemite
***************
$53 USD |Los Angeles International| Fresno Yosemite
***************
$41 USD |Houston George Bush Intercntl.| Sacramento International
***************
$325 USD |Houston George Bush Intercntl.| Sacramento International
***************
$166 USD |New York John F. Kennedy| Sacramento International
***************
$74 USD |Los Angeles International| Sacramento International
***************
$79 USD |Los Angeles International| Sacramento International
***************
$87 USD |Dallas Fort Worth International| Sacramento International
***************
$261 USD |Dallas Fort Worth International| Sacramento International
***************
$51 USD |Denver International| Sacramento International
***************
$39 USD |Houston George Bush Intercntl.| Hartford Bradley International
***************
$188 USD |Los Angeles International| Hartford Bradley International
***************
$63 USD |Dallas Fort Worth International| Hartford Bradley International
***************
$334 USD |Dallas Fort Worth International| Hartford Bradley International
***************
$38 USD |Denver International| Hartford Bradley International
***************
$168 USD |Denver International| Hartford Bradley International
***************
$100 USD |New York John F. Kennedy| Key West International
***************
$136 USD |Dallas Fort Worth International| Key West International
***************
$400 USD |Dallas Fort Worth International| Key West International
***************
$97 USD |New York John F. Kennedy| Boise
***************
$109 USD |Los Angeles International| Boise
***************
$112 USD |Dallas Fort Worth International| Boise
***************
$132 USD |Dallas Fort Worth International| Boise
***************
$121 USD |Houston George Bush Intercntl.| Austin-Bergstrom
***************
$144 USD |New York John F. Kennedy| Austin-Bergstrom
***************
$50 USD |Los Angeles International| Austin-Bergstrom
***************
$37 USD |Denver International| Austin-Bergstrom
***************
$150 USD |New York John F. Kennedy| San Antonio International
***************
$132 USD |Los Angeles International| San Antonio International
***************
$121 USD |Dallas Fort Worth International| San Antonio International
***************
$43 USD |Denver International| San Antonio International
***************
$87 USD |Dallas Fort Worth International| Midland Odessa Regional
***************
$196 USD |Dallas Fort Worth International| Midland Odessa Regional

In [46]:
# Check list length and json format
dfdf = pd.json_normalize(listlist)
print(f"Total list length: {len(listlist)}")
listlist[2]

Total list length: 300

{'Quotes': [{'QuoteId': 1,
   'MinPrice': 40,
   'Direct': True,
   'OutboundLeg': {'CarrierIds': [1467],
    'OriginId': 65368,
    'DestinationId': 58440,
    'DepartureDate': '2021-09-03T00:00:00'},
   'QuoteDateTime': '2021-08-11T16:56:00'}],
 'Carriers': [{'CarrierId': 1467, 'Name': 'Spirit Airlines'}],
 'Places': [{'Name': 'Houston George Bush Intercntl.',
   'Type': 'Station',
   'PlaceId': 58440,
   'IataCode': 'IAH',
   'SkyscannerCode': 'IAH',
   'CityName': 'Houston',
   'CityId': 'HOUA',
   'CountryName': 'United States'},
  {'Name': 'Los Angeles International',
   'Type': 'Station',
   'PlaceId': 65368,
   'IataCode': 'LAX',
   'SkyscannerCode': 'LAX',
   'CityName': 'Los Angeles',
   'CityId': 'LAXA',
   'CountryName': 'United States'},
  {'Name': 'Los Angeles',
   'Type': 'City',
   'PlaceId': 3137681,
   'SkyscannerCode': 'LAXA',
   'CityId': 'LAXA',
   'CountryName': 'United States'}],
 'Currencies': [{'Code': 'USD',
   'Symbol': '$',
   'ThousandsSeparator': ',',
   'DecimalSeparator': '.',
   'SymbolOnLeft': True,
   'SpaceBetweenAmountAndSymbol': False,
   'RoundingCoefficient': 0,
   'DecimalDigits': 2}],
 'Routes': [{'Price': 40,
   'QuoteDateTime': '2021-08-11T16:56:00',
   'OriginId': 3137681,
   'DestinationId': 58440,
   'QuoteIds': [1]}]}

## Turn JSON into dataframe

In [62]:
# Create list to cross-reference airport ID and IATA code
iata_list = {}

for flight in listlist:
    try:
        iata_list[flight['Places'][0]["PlaceId"]] = flight['Places'][0]["IataCode"]
        iata_list[flight['Places'][1]["PlaceId"]] = flight['Places'][1]["IataCode"]
    except:
        pass
    
print(len(iata_list))

53

In [61]:
flight_list = []

for flight in listlist:
    flight_dict = {}
    try:
        
        # Add airport name and IATA code
        ori = flight['Quotes'][0]["OutboundLeg"]["OriginId"]
        dest = flight['Quotes'][0]["OutboundLeg"]["DestinationId"]
        flight_dict['origin_name'] = airports[ori]
        flight_dict['origin_iata'] = iata_list[ori]
        flight_dict['dest_name'] =  airports[dest]
        flight_dict['dest_iata'] = iata_list[dest]
        
        # Add price and carrier
        flight_dict['min_price_usd'] = flight['Quotes'][0]['MinPrice']
        flight_dict['carrier'] = flight['Carriers'][0]['Name']
        
        flight_list.append(flight_dict)
    
    except:
        pass
    
flightflight = pd.DataFrame(flight_list)
print(f" Length: {len(flight_list)} entries")
flightflight

 Length: 188 entries

,origin_name,origin_iata,dest_name,dest_iata,min_price_usd,carrier
0,New York John F. Kennedy,JFK,Houston George Bush Intercntl.,IAH,88,jetBlue
1,Los Angeles International,LAX,Houston George Bush Intercntl.,IAH,40,Spirit Airlines
2,Dallas Fort Worth International,DFW,Houston George Bush Intercntl.,IAH,51,Spirit Airlines
3,Denver International,DEN,Houston George Bush Intercntl.,IAH,25,Spirit Airlines
4,Houston George Bush Intercntl.,IAH,New York John F. Kennedy,JFK,110,Spirit Airlines
...,...,...,...,...,...,...
183,New York John F. Kennedy,JFK,San Antonio International,SAT,150,jetBlue
184,Los Angeles International,LAX,San Antonio International,SAT,132,Alaska Airlines
185,Dallas Fort Worth International,DFW,San Antonio International,SAT,121,Spirit Airlines
186,Denver International,DEN,San Antonio International,SAT,43,Frontier Airlines
187,Dallas Fort Worth International,DFW,Midland Odessa Regional,MAF,87,Alaska Airlines

In [57]:
# Check to make sure data came through properly
origin_group = flightflight.groupby('origin_name').nunique()
origin_group

flightflight['dest_name'].nunique()

52

## Import airport GPS coordinates

In [90]:
# Inport and clean GPS data
where_my_airport = pd.read_csv("https://datahub.io/core/airport-codes/r/airport-codes.csv")
where_my_airport = where_my_airport.drop(['municipality','ident','type','elevation_ft','continent','iso_country','iso_region','name','gps_code','local_code'], axis = 1)
where_my_airport = where_my_airport.dropna()
where_my_airport

      iata_code                             coordinates
223         UTK                      169.852005, 11.222
441         OCA       -80.274803161621, 25.325399398804
598         PQS                  -162.899994, 61.934601
677         CSE                  -106.928341, 38.851918
1094        JCY  -98.62249755859999, 30.251800537100003
...         ...                                     ...
57412       DLC    121.53900146484375, 38.9656982421875
57413       TNH            125.703333333, 42.2538888889
57414       SHE  123.48300170898438, 41.639801025390625
57415       YNJ            129.451004028, 42.8828010559
57416       YKH                     122.3586, 40.542524

[9225 rows x 2 columns]

## Merge flight data with GPS coordinates

In [92]:
# Merge origin GPS
flight_df = pd.merge(flightflight,where_my_airport,how="inner",left_on="origin_iata",right_on="iata_code")
flight_df = flight_df.rename({'coordinates': 'origin_gps'}, axis='columns')

# Merge destination gps
flight_df = pd.merge(flight_df,where_my_airport,how="inner",left_on="dest_iata",right_on="iata_code")
flight_df = flight_df.rename({'coordinates': 'dest_gps'}, axis='columns')

# Clean
flight_df = flight_df.drop(['iata_code_y','iata_code_x'], axis = 1)

flight_df

,origin_name,origin_iata,dest_name,dest_iata,min_price_usd,carrier,origin_gps,dest_gps
0,New York John F. Kennedy,JFK,Houston George Bush Intercntl.,IAH,88,jetBlue,"-73.7789, 40.639801","-95.34140014648438, 29.984399795532227"
1,Los Angeles International,LAX,Houston George Bush Intercntl.,IAH,40,Spirit Airlines,"-118.407997, 33.942501","-95.34140014648438, 29.984399795532227"
2,Dallas Fort Worth International,DFW,Houston George Bush Intercntl.,IAH,51,Spirit Airlines,"-97.038002, 32.896801","-95.34140014648438, 29.984399795532227"
3,Denver International,DEN,Houston George Bush Intercntl.,IAH,25,Spirit Airlines,"-104.672996521, 39.861698150635","-95.34140014648438, 29.984399795532227"
4,New York John F. Kennedy,JFK,Los Angeles International,LAX,138,Alaska Airlines,"-73.7789, 40.639801","-118.407997, 33.942501"
...,...,...,...,...,...,...,...,...
183,Dallas Fort Worth International,DFW,Tucson International,TUS,144,United,"-97.038002, 32.896801","-110.938053, 32.115004"
184,Denver International,DEN,Tucson International,TUS,249,Frontier Airlines,"-104.672996521, 39.861698150635","-110.938053, 32.115004"
185,Denver International,DEN,Amarillo International,AMA,121,Frontier Airlines,"-104.672996521, 39.861698150635","-101.706001, 35.219398"
186,Denver International,DEN,Cheyenne,CYS,1765,Linear Air,"-104.672996521, 39.861698150635","-104.8119965, 41.15570068"
187,Houston George Bush Intercntl.,IAH,Huntsville International,HSV,109,United,"-95.34140014648438, 29.984399795532227","-86.775100708008, 34.637199401855"

### [x] Data

### [   ] pd.to_sql(name="dbdb", index=false, con = conn)

### [   ] Flask API

* query db, jsonify, profit
* you can cheat here and just feed in a json of your choice instead of querying the database while you get the database going...


### [   ] Put on map :smile:

#

#

## Compare prices on different days (no longer using)

In [114]:
# import time, datetime, dateutil
# import pandas as pd
# import requests

# # Origin airport:
# origin = "HOUA-sky" 

# # Destination airports: 
# single_dest = "JFK-iata"

# # Enter date as YYYY-MM-DD:
# source_begin_date = "2021-09-06"
# source_end_date =  "2021-10-03"  
# daterange = pd.date_range(source_begin_date, source_end_date)

# # Other parameters
# currancy = "USD"
# originCountry = "US"
# locale = "en-US"
# baseURL = "https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com/apiservices/browsequotes/v1.0/"

In [44]:
# calendar = {}

# print("From: Houston")

# for single_date in daterange:
#     myurl = baseURL + originCountry + "/" + currancy + "/" + locale + "/" + origin + "/"  + single_dest + "/" + "2021-09-06"
#     response = requests.request("GET", myurl, headers=headers)
#     results = json.loads(response.text)
        
#     # Check if there are no flights
#     if("Quotes" in results):
#         for Places in results["Places"]:
#             # Add the airport in the dictionary.
#             airports[Places["PlaceId"]] = Places["Name"] 
#         for Quotes in results["Quotes"]:
#             print("***************")
#             print(single_date.strftime("%d-%b %a"))
#             ori = Quotes["OutboundLeg"]["OriginId"]
#             dest = Quotes["OutboundLeg"]["DestinationId"]
#             price = Quotes["MinPrice"]
#             print(f"${price} USD | {airports[dest]} ")
#             calendar[single_date.strftime("%d-%b %a")] = price

# print("-------------------------------")
# print("DONE!")
# print(f"{len(calendar)} total results")

In [45]:
# cal_df = pd.DataFrame(calendar, index = ['a'])
# cal_df = cal_df.transpose()
# cal_df = cal_df.reset_index()
# cal_df = cal_df.rename(columns={"index": "Date", "a": "Cost USD"})
# cal_df

# Old code

In [ ]:
# # Origin airport:
# origin = "HOU-iata"

# # Destination airports: 
# destinations = ["JFK-iata","LAX-iata","DFW-iata","DEN-iata","ATL-iata","ORD-iata","CLT-iata","LAS-iata","PHX-iata","PCO-iata","SEA-iata","MIA-iata","FLL-iata","SFO-iata","EWR-iata","MSP-iata","DTW-iata","BOS-iata","SLC-iata","PHL-iata","BWI-iata","TPA-iata","SAN-iata","AMA-iata","IAD-iata","BNA-iata","ABQ-iata","PDX-iata","DSM-iata","MSY-iata","BIL-iata","FAR-iata","MAF-iata","LBB-iata","BTV-iata","ROA-iata","MKE-iata","MSN-iata","GRB-iata","CYS-iata","JAC-iata","ELP-iata","CRP-iata","BHM-iata","HSV-iata","TUS-iata","LIT-iata","FAT-iata","SMF-iata","GJT-iata","BDL-iata","EYW-iata","PFN-iata","BOI-iata","EVV-iata","AZO-iata","AUS-iata","SAT-iata","MAF-iata"]

# # Enter date as YYYY-MM-DD:
# date = "2021-09-23"

# # Other parameters
# currancy = "USD"
# originCountry = "US"
# locale = "en-US"
# baseURL = "https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com/apiservices/browseroutes/v1.0/"

In [ ]:
# airports = {}
# flights = {}
# listlist = []
# from time import sleep

# print("From Houston:")

# for destination in destinations:
#     myurl = baseURL + originCountry + "/" + currancy + "/" + locale + "/" + origin + "/"  + destination + "/" + date
#     response = requests.request("GET", myurl, headers=headers)
#     results = json.loads(response.text)
#     listlist.append(results)

# #     Check if there are no flights
#     if("Quotes" in results):
#         for Places in results["Places"]:
#             # Add the airport in the dictionary.
#             airports[Places["PlaceId"]] = Places["Name"] 
#         for Quotes in results["Quotes"]:
#             print("***************")
#             ori = Quotes["OutboundLeg"]["OriginId"]
#             dest = Quotes["OutboundLeg"]["DestinationId"]
#             price = Quotes["MinPrice"]
#             print(f"${price} USD | {airports[ori]} --> {airports[dest]} ")
#             flights[airports[dest]] = price
#             sleep(2)
#     #             print(airports)

# print("-------------------------------")
# print("DONE!")
# print(f"{len(flights)} total results")

In [ ]:
#  #Airports where we can fly from: houston
# source_array = {"HOUA-sky"} 

# # Our destination airports: 
# destination_array = {"JFK-sky", "LAX-sky", "DFW-sky", "DEN-sky"}

# ### ( Note that technically these are Python **sets** and not arrays.)

# # And to make our life easier
# rootURL = "https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com/apiservices/browsequotes/v1.0/"

In [ ]:
# airports = { }
# for destination in destination_array:
#     for source in source_array:
#         myurl = rootURL + originCountry + "/" + currancy + "/" + locale + "/" + source + "/"  + destination + "/" + "2021-09-23"
#         response = requests.request("GET", myurl, headers=headers)
#         temp = json.loads(response.text)
        
#         # This checks if we have a quote or there were no flights
#         if("Quotes" in temp):
#             for Places in temp["Places"]:
#                 # Add the airport in the dictionary.
#                 airports[Places["PlaceId"]] = Places["Name"] 
#             for Quotes in temp["Quotes"]:
#                 print("************")
#                 # print("%s --> to  -->%s" %(origin,destination))
#                 ori = Quotes["OutboundLeg"]["OriginId"]
#                 dest = Quotes["OutboundLeg"]["DestinationId"]
#                 # Look for Airports in the dictionary
#                 print("Journy:  %s  --> %s"%(airports[ori],airports[dest]))
#                 print("Price: %s EUR" %Quotes["MinPrice"])

In [ ]:
# flight_list = []
# for flight in listlist:
#     flight_dict = {}
#     try:
# #         flight_dict['orig_lat'] = my_google_results[airport]
#         flight_dict['min_price_usd'] = flight['Quotes'][0]['MinPrice']
#         flight_dict['origin_name'] = flight['Places'][0]['Name']
#         flight_dict['origin_code'] = flight['Places'][0]['IataCode']
#         flight_dict['dest_name'] =  flight['Places'][1]['Name']
#         flight_dict['dest_code'] =  flight['Places'][1]['IataCode']
#         flight_list.append(flight_dict)
#     except:
#         pass
# flightflight = pd.DataFrame(flight_list)
# print(len(flight_list))
# flightflight

In [ ]:
# flights_df = pd.DataFrame(flights, index =['a'])
# flights_df = flights_df.transpose()
# flights_df = flights_df.reset_index()
# flights_df = flights_df.rename(columns={"index": "Destination", "a": "Cost USD"})
# flights_df

In [ ]:
# import time, datetime, dateutil
# import pandas as pd

# source_begin_date = "2021-09-06"
# source_end_date =  "2021-10-03"  
# daterange = pd.date_range(source_begin_date, source_end_date)
# airports = { }
# maxbudget = 400

In [ ]:
# class findingCheapestFlights:
    
#     def __init__(self, originCountry = "DE", currency = "EUR", locale = "en-US", rootURL="https://skyscanner-skyscanner-flight-search-v1.p.rapidapi.com"):
#         self.currency = currency
#         self.locale =  locale
#         self.rootURL = rootURL
#         self.originCountry = originCountry

#     def setHeaders(self, headers):
#         self.headers =  headers

#     def browseQuotes(self, source, destination, date):
#         quoteRequestPath = "/apiservices/browsequotes/v1.0/"
#         browseQuotesURL = self.rootURL + quoteRequestPath + self.originCountry + "/" + self.currency + "/" + self.locale + "/" + source + "/" + destination + "/" + date.strftime("%Y-%m-%d")
#         response = requests.request("GET", url = browseQuotesURL, headers = self.headers)
#         resultJSON = json.loads(response.text)
#         return resultJSON

In [ ]:
# import time
# cheapest_flight_finder = findingCheapestFlights()
# cheapest_flight_finder.setHeaders(headers)

# total_compute_time = 0.0
# total_request_time = 0.0

# function_start = time.time()
# for single_date in daterange:
#     for destination in destination_array:
#         for source in source_array:
#             request_start = time.time()
#             resultJSON = cheapest_flight_finder.browseQuotes(source, destination,single_date)
#             request_end = time.time()
#             if("Quotes" in resultJSON):
#                 for Places in resultJSON["Places"]:
#                     # Add the airport in the dictionary.
#                     airports[Places["PlaceId"]] = Places["Name"] 
#                 for Quotes in resultJSON["Quotes"]:
#                     if(Quotes["MinPrice"]<maxbudget):                        
#                         print("************")
#                         print(single_date.strftime("%d-%b %a"))
#                         # print("%s --> to  -->%s" %(origin,destination))
#                         source = Quotes["OutboundLeg"]["OriginId"]
#                         dest = Quotes["OutboundLeg"]["DestinationId"]
#                         # Look for Airports in the dictionary
#                         print("Journy:  %s  --> %s"%(airports[source],airports[dest]))
#                         print("Price: %s EUR" %Quotes["MinPrice"])
#             calculation_end = time.time()
#             total_compute_time += calculation_end - request_end 
#             total_request_time += request_end - request_start
# print("\nBenchmark Stats :")
# print("Time spent in computing: %f seconds"%total_compute_time )
# print("Time spent in requesting: %f seconds"%total_request_time )
# print("Time spent in program: %f seconds"%(time.time()-function_start))